name = "duplicate"
output = "duplicate.json"
hyperfine_params = [
    "hyperfine", "--runs", "5", "-N",
    "-L", "ifile", "Cargo.toml,README.md",
    "-L", "ofile", "/tmp/test.raw",
]

[run.past]
hashes = ["master", "asdfas"] # can be hash, tag or branch
command_params = ["sqsh-cli", "duplicate", "--input", "{ifile}", "--output", "{ofile}"]

[run.reference]
hashes = ["sdfafs"]
command_params = ["sqsh-cli", "duplicate", "--input", "{ifile}", "--output", "{ofile}"]

[run.control]
command_params = ["dd", "if={ifile}", "of={ofile}"]
